[package]
name = "string-art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.25"
image = "0.24.7"
rayon = "1.5.1"
ndarray = { version = "*", features = ["rayon"] }
